version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./dockerize/app/php.dockerfile
    image: crmproject-app
    container_name: crmproject
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - adminer
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: nginx-webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./dockerize/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${APP_NAME:-laravel_db}
      MYSQL_USER: ${APP_NAME:-laravel_usr}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./dockerize/mysql/data:/var/lib/mysql
      - ./dockerize/mysql/my.cnf:/etc/mysql/conf.d/mysql-custom.cnf
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local